import React, { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";

const ApprovePayslips = () => {
  const [payslips, setPayslips] = useState([]);

  useEffect(() => {
    fetchPayslips();
  }, []);

  const fetchPayslips = async () => {
    try {
      const token = localStorage.getItem("token");

     const res = await axios.get(
  "http://localhost:8000/api/payroll",
        {
          headers: { Authorization: `Bearer ${token}` },
        }
      );

      console.log("Payslips:", res.data);
      setPayslips(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  const handleStatus = async (id, status) => {
    try {
      const token = localStorage.getItem("token");

      await axios.put(
        `http://localhost:8000/api/payroll/status/${id}`,
        { status },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      fetchPayslips();
    } catch (err) {
      console.error(err);
      alert("Error updating status ❌");
    }
  };

  const handleDownload = (payslip) => {
  const doc = new jsPDF();

  doc.setFontSize(16);
  doc.text("Salary Slip", 20, 20);

  doc.setFontSize(12);
  doc.text(`Employee: ${payslip.employeeName}`, 20, 40);
  doc.text(
    `Period: ${payslip.startDate} - ${payslip.endDate}`,
    20,
    50
  );

  // ✅ FIX: remove ₹ symbol
  doc.text(`HRA: Rs. ${payslip.hra}`, 20, 70);
  doc.text(`Bonus: Rs. ${payslip.bonus}`, 20, 80);
  doc.text(`Deductions: Rs. ${payslip.deductions}`, 20, 90);

  // ✅ FIX: correct field name
 const overtimeValue =
  payslip.overtimeHours ??
  payslip.overtime ??
  0;

doc.text(
  `Overtime: ${Number(overtimeValue).toFixed(2)}`,
  20,
  100
);

  doc.text(`Extra Orders: ${payslip.extraOrders}`, 20, 110);

  // ✅ FIX: decimal issue
  doc.text(
    `Net Salary: Rs. ${Number(payslip.netSalary).toFixed(2)}`,
    20,
    130
  );

  const fileName = `${payslip.employeeName.replace(/\s+/g, "_")}_Payslip.pdf`;
doc.save(fileName);
};

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        
        <h1 style={styles.title}>
          Approve Employee Payslips
        </h1>

        <div style={styles.infoBox}>
          <p>
           This section allows Admin to <b>Approve or Reject Payslips</b> generated by HR.
           You can view <b>Pending, Approved, and Rejected Payslips</b> here.
          </p>
        </div>

        <table style={styles.table}>
          <thead>
            <tr style={styles.tableHeaderRow}>
              <th style={styles.cell}>Employee</th>
              <th style={styles.cell}>Department</th>
              <th style={styles.cell}>Month</th>
              <th style={styles.cell}>Net Salary</th>
              <th style={styles.cell}>Status</th>
              <th style={styles.cell}>Actions</th>
            </tr>
          </thead>

          <tbody>
            {payslips.map((slip) => (
              <tr key={slip._id}>
                
                <td style={styles.cell}>{slip.employeeName}</td>

                <td style={styles.cell}>
                  {slip.employeeId?.department || "N/A"}
                </td>

                <td style={styles.cell}>
                {(() => {
                  const dstr = slip.startDate || "";
                  const normalized = /T|Z/.test(dstr) || dstr.includes(" ") ? dstr : dstr + "T00:00:00";
                  return new Date(normalized).toLocaleDateString("en-US", {
                    month: "short",
                    year: "numeric",
                  });
                })()}
                </td>

               <td style={styles.cell}>
                  ₹ {Number(slip.netSalary).toFixed(2)}
               </td>

                <td style={styles.cell}>
                 <span
  style={{
    ...styles.statusBadge,
    background:
      slip.status === "approved"
        ? "#d1fae5"
        : slip.status === "rejected"
        ? "#fee2e2"
        : "#fef3c7",
    color:
      slip.status === "approved"
        ? "#065f46"
        : slip.status === "rejected"
        ? "#991b1b"
        : "#92400e",
  }}
>
  {slip.status}
</span>
                </td>

                <td style={{ ...styles.cell, display: "flex", gap: "8px" }}>
  {slip.status === "pending" && (
    <>
      <button
        style={styles.approveBtn}
        onClick={() => handleStatus(slip._id, "approved")}
      >
        Approve
      </button>

      <button
        style={styles.rejectBtn}
        onClick={() => handleStatus(slip._id, "rejected")}
      >
        Reject
      </button>
    </>
  )}

  <button
    style={styles.downloadBtn}
    onClick={() => handleDownload(slip)}
  >
    Download
  </button>
</td>
              </tr>
            ))}
          </tbody>
        </table>

      </div>
    </div>
  );
};

export default ApprovePayslips;

const styles = {
  // ✅ GRADIENT BACKGROUND (LIKE YOUR OTHER PAGES)
  container: {
    minHeight: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    background: "linear-gradient(135deg, #b4dffb, #d7dbe0)",
    padding: "60px",
  },

  // ✅ CARD WRAPPER
  card: {
    width: "95%",
    maxWidth: "1200px",
    background: "#ffffff",
    padding: "25px",
    borderRadius: "15px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.2)",
  },

  title: {
    textAlign: "center",
    fontSize: "32px",
    fontWeight: "bold",
    color: "#a21caf",
    marginBottom: "20px",
  },

  infoBox: {
    background: "#dbeafe",
    padding: "15px",
    borderRadius: "10px",
    marginBottom: "25px",
    borderLeft: "5px solid #4d7ac2",
    fontSize: "15px",
   
  },

  table: {
    width: "100%",
    borderCollapse: "collapse",
  },

  tableHeaderRow: {
    background: "linear-gradient(90deg, #3b82f6, #06b6d4)",
    color: "white",
    textAlign: "left",
  },

  cell: {
    padding: "12px",
  },

  approveBtn: {
    background: "#10b981",
    color: "white",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
  },

  rejectBtn: {
    background: "#ef4444",
    color: "white",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
  },

  downloadBtn: {
    background: "#3b82f6",
    color: "white",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
  },

  pendingBadge: {
    background: "#fef3c7",
    color: "#92400e",
    padding: "5px 10px",
    borderRadius: "20px",
    fontWeight: "bold",
    fontSize: "12px",
  },

  statusBadge: {
  padding: "5px 10px",
  borderRadius: "20px",
  fontWeight: "bold",
  fontSize: "12px",
},
};